name: Edit wikitext
description: Edit an existing page with wikitext.
title: "[Edit]: "
labels: ["edit", "wikitext"]
assignees:
  - aadenboy
body:
  - type: markdown
    attributes:
      value: |
        This is used to edit a page by modifying or appending wikitext directly. You will need to get the source for the page by clicking "View source".
        If you aren't sure on how to use wikitext, visit https://www.mediawiki.org/wiki/Wikitext for instructions. You may want to use the "Edit suggestion" template instead.
  - type: input
    id: page
    attributes:
      label: Page to edit
      description: Which page are you editing?
      placeholder: ex. Main Page
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Descrpition
      description: Give a description or a brief summary of what your edit is.
      placeholder: Lorem ipsum dolor sit amet
    validations:
      required: true
  - type: dropdown
    id: edittype
    attributes:
      label: Edit type
      description: How is your edit going to be implemented?
      options:
        - Minor edit (add the "minor" tag)
        - Add new content
        - Modify existing content
        - Remove existing content
        - Replace existing content
        - Replace entire page
      default: 0
    validations:
      required: true
  - type: textarea
    id: wikitext
    attributes:
      label: Wikitext
      description: Put the wikitext for your edit here. Preferrably, include the entire source of the page.
      placeholder: Lorem ipsum dolor sit amet
    validations:
      required: true
  - type: markdown
    attributes:
      value: Note that anything you contribute to the Aadenboy Wiki is to be licensed under CC BY-SA 4.0.